# Generated by Django 5.2.3 on 2025-06-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_package_packageimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
